Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.74s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.63s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.80s/it]
[Memory(location=cache/joblib)]: Flushing completely the cache
Traceback (most recent call last):
  File "/sorgin1/users/jbarrutia006/viper/main_project.py", line 318, in <module>
    main()
  File "/sorgin1/users/jbarrutia006/viper/main_project.py", line 208, in main
    dataset = get_dataset(config.dataset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sorgin1/users/jbarrutia006/viper/datasets/__init__.py", line 16, in get_dataset
    dataset = RefCOCODataset(**config_dataset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sorgin1/users/jbarrutia006/viper/datasets/refcoco.py", line 32, in __init__
    with open(ref_file, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: './data/refcoco/refcoco/refs(unc).p'
srun: error: localhost: task 0: Exited with exit code 1
